FROM pytorch/pytorch:2.7.0-cuda12.8-cudnn9-runtime
WORKDIR /testing
COPY requirements.txt requirements.txt
RUN apt-get update && apt-get install -y --no-install-recommends build-essential
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    ffmpeg
RUN pip3 install -r requirements.txt
COPY . .
EXPOSE 6969
RUN rm requirements.txt
ENV PYTHONPATH "/testing/app:/testing:${PYTHONPATH}"
ENV APP_SETTINGS=config.TestingConfig
ENV DATABASE_URL=postgresql://user:password@db:5433/mydb
CMD ["sh", "-c", "coverage run -m pytest && coverage report --ignore-errors --omit='tests/*'"]