# syntax=docker/dockerfile:1.7-labs
FROM pytorch/pytorch:2.7.0-cuda12.8-cudnn9-runtime
WORKDIR /app
COPY requirements.txt requirements.txt
RUN apt-get update && apt-get install -y --no-install-recommends build-essential
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    ffmpeg
RUN pip3 install -r requirements.txt
COPY --exclude=tests/ . .
EXPOSE 6969
RUN rm requirements.txt
ENV APP_SETTINGS=config.DevelopmentConfig
ENV DATABASE_URL=postgresql://user:password@db:5433/mydb
CMD ["python", "run.py"]