FROM python:3.13.3-slim
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .
EXPOSE 6969
RUN rm requirements.txt
ENV APP_SETTINGS=config.DevelopmentConfig
ENV DATABASE_URL=sqlite:///app.db
CMD ["python", "run.py"]