name: CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      APP_SETTINGS: config.DevelopmentConfig

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends build-essential \
            libgl1 libglib2.0-0 libsm6 libxext6 ffmpeg


    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report --ignore-errors --omit='tests/*'
